config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_profiles do
    member do
      get :properties
      get :add_contact
    end
    get :contacts, on: :collection
  end

  resources :properties

  resources :messages, only: [:index, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index', as: :root
end

app/views/shared/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% images.size.times do |i|  %>
      <li data-target="#myCarousel" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% images.each_with_index do |image, index| %>
      <div class="item <%= 'active' if index == 0 %>">
        <%= link_to image.attachment.url, data: { lightbox: true } do %>
          <%= image_tag image.attachment.url(:large) %>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Siguiente</span>
  </a>
</div>

app/views/shared/_copyrights_footer.html.erb
<footer class="row copyright-footer">
  <div class="col-md-10 col-md-offset-2 col-md-pull-1 col-sm-12">
    <p class="terms">
      <%= t 'footer.copyright' %> |
      <%= link_to t('footer.privacy'), 'privacy_policy_path', target: '_blank' %> |
      <%= link_to t('footer.terms'), 'terms_of_service_path', target: '_blank' %> |
    </p>
  </div>
</footer>

app/views/shared/_menu_links.html.erb
<li>
  <%= link_to user_profiles_path do %>
    <%= fa_icon 'globe' %><span class="text">Comunidad</span>
  <% end %>
</li>
<li>
  <%= link_to properties_path do %>
    <%= fa_icon 'building' %><span class="text">Propiedades</span>
  <% end %>
</li>
<% if user_signed_in? %>
  <% if current_user.has_profile? %>
    <li>
      <%= link_to current_user.profile do %>
        <%= fa_icon 'user' %><span class="text">Mi Perfil</span>
      <% end %>
    </li>
  <% end %>
  <li>
    <%= link_to contacts_user_profiles_path do %>
      <%= fa_icon 'users' %><span class="text">Mis contactos</span>
    <% end %>
  </li>
  <li>
    <%= link_to messages_path do %>
      <%= fa_icon 'inbox' %><span class="text">Mensajes</span>
    <% end %>
  </li>
  <li>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <%= fa_icon 'sign-out' %><span class="text">Cerrar Sesión</span>
    <% end %>
  </li>
<% else %>
  <li>
    <%= link_to new_user_session_path do %>
      <%= fa_icon 'sign-in' %><span class="text">Iniciar Sesión</span>
    <% end %>
  </li>
  <li>
    <%= link_to new_user_registration_path do %>
      <%= fa_icon 'user-plus' %><span class="text">Registrarse</span>
    <% end %>
  </li>
<% end %>

app/views/shared/_model_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%#= image_tag 'co-logo.png' %>
        Comisionista Online
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#public-menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if params[:controller] == 'home' %>
            <li>
              <%= link_to user_profiles_path do %>
                <span class="glyphicon glyphicon-check"></span> Entrar
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Cerrar sesión
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> Registrarse
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Iniciar sesión
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar_inner.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%#= image_tag 'co-logo.png' %>
        Comisionista Online
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#public-menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="public-menu">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'shared/menu_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar_public.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%#= image_tag 'co-logo.png' %>
        Comisionista Online
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#public-menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="public-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if params[:controller] == 'home' %>
            <li>
              <%= link_to user_profiles_path do %>
                <span class="glyphicon glyphicon-check"></span> Entrar
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Cerrar sesión
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> Registrarse
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Iniciar sesión
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_side_menu.html.erb
<div class="overlay"></div>

<nav class="navbar navbar-inverse navbar-fixed-top hidden-xs" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to root_path do %>
        <%= fa_icon 'home' %><span class="text">Comisionista Online</span>
      <% end %>
    </li>
    <%= render 'shared/menu_links' %>
  </ul>
</nav>