config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_profiles do
    member do
      get :properties
      get :add_contact
    end
    get :contacts, on: :collection
  end

  resources :properties

  resources :messages, only: [:index, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index', as: :root
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord

  MAIN_CITIES = %w[Medellin Bogotá Cali Bucaramanga Armenia]
  ROLES = %w[Comisionista Propietario Inversionista]

  belongs_to :user
  has_many :properties, through: :user

  has_attached_file :avatar, styles: { medium: "300x200>", thumb: "100x65>" }, default_url: "/images/missing_:style.png"
  validates_attachment :avatar, presence: true, content_type: { content_type: %w[image/jpeg image/png image/gif] }, size: { in: 0..5.megabytes }

  validates :user, :first_name, :last_name, :birthdate, :about, :city, :phone, :role, presence: true
  validates :role, inclusion: { in: ROLES, allow_blank: true }
  validates :city, inclusion: { in: MAIN_CITIES, allow_blank: true }
  validates :user_id, uniqueness: true

  delegate :email, to: :user

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  load_and_authorize_resource
  skip_load_resource only: :contacts

  skip_before_action :check_registration_finished, only: [:new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
  end

  # GET /user_profiles/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'Su perfil ha sido creado exitosamente' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'Su perfil ha sido actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def properties
    @properties = @user_profile.properties
    @title = "Propiedades de #{@user_profile.full_name}"
    render 'properties/index'
  end

  def add_contact
    if user = @user_profile.user
      current_user.contacts << user
      @messages = {success: 'Contacto agregado con éxito.'}
    else
      @messages = {error: 'No se pudo a agregar este contacto'}
    end
  end

  def contacts
    @user_profiles = UserProfile.where(user_id: current_user.contacts)
    @page_title = 'Mis contactos'
    render :index
  end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_profile_params
    params.require(:user_profile).permit(:first_name, :last_name, :birthdate, :about, :experience, :city, :phone, :role,
      :avatar).merge user: current_user
  end

end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_for user_profile do |form| %>
  <%= render 'shared/model_errors', resource: user_profile %>

  <% if user_profile.avatar.present? %>
    <div class="form-group col-xs-12">
      <%= link_to user_profile.avatar.url, data: { lightbox: true } do %>
        <%= image_tag user_profile.avatar.url(:medium) %>
      <% end %>
    </div>
  <% end %>

  <div class="form-group col-sm-6">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="clearfix">
    <div class="form-group col-sm-6">
      <%= form.label :role %>
      <%= form.select :role, UserProfile::ROLES, {include_blank: true}, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-6 <%= 'hidden-soft' if user_profile.experience != 'Comisionista' %>">
      <%= form.label :experience %>
      <%= form.number_field :experience, class: 'form-control', min: 1, max: 70 %>
    </div>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :city %>
    <%= form.select :city, UserProfile::MAIN_CITIES, {}, class: 'form-control' %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :phone %>
    <%= form.phone_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label :birthdate %>
    <%= form.text_field :birthdate, class: 'form-control birthdate', readonly: true %>
  </div>

  <div class="form-group col-xs-12">
    <%= form.label :about %>
    <%= form.text_area :about, rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group col-xs-12">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, accept: 'image/png,image/gif,image/jpeg' %>
  </div>

  <div class="form-group col-xs-12">
    <%= form.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Cambiar contraseña', edit_user_registration_path, class: 'pull-right' if user_profile.persisted? %>
  </div>

<% end %>

app/views/user_profiles/add_contact.js.erb
<% @messages.each do |type, content| %>
  toastr['<%= type %>']('<%= content %>');
<% end %>
$('#add-contact-button').remove();

app/views/user_profiles/edit.html.erb
<h1>Editar perfil de usuario</h1>

<%= render 'form', user_profile: @user_profile %>

<p class="pull-right">
  <%= link_to 'Perfil', @user_profile, class: 'btn btn-primary' %>
  <%= link_to 'Volver', user_profiles_path, class: 'btn btn-default' %>
  <br>
  <br>
</p>

app/views/user_profiles/index.html.erb
<div class="col-xs-12 no-padding header">
  <h1><%= @page_title || 'Usuarios en la comunidad' %></h1>
</div>

<div class="row co-grid">
  <% @user_profiles.each do |user_profile| %>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 grid-item-container <%= user_profile.role.downcase %>">
      <div class="grid-item">
        <div class="image-container">
          <%= link_to user_profile.avatar.url, data: { lightbox: true, title: 'Foto de perfil' } do %>
            <%= image_tag user_profile.avatar.url(:medium) %>
          <% end %>
        </div>
        <%= link_to user_profile, class: 'data', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Ir al perfil' do %>
          <h4><%= user_profile.full_name %></h4>
          <span class="role"><%= user_profile.role %></span>
          <br/>
          <% if user_profile.experience %>
            <%= user_profile.experience %> años de experiencia en el sector
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/user_profiles/new.html.erb
<h1>Por favor termina tu registro</h1>

<%= render 'form', user_profile: @user_profile %>

app/views/user_profiles/show.html.erb
<div class="profile-images-container">
  <%= image_tag 'profile-bg.jpg', class: 'background' %>
  <%= image_tag 'co-logo.png', class: 'co-logo' %>
  <div class="user-logo">
    <%= link_to @user_profile.avatar.url, data: { lightbox: true, title: 'Foto de perfil' } do %>
      <%= image_tag @user_profile.avatar.url(:medium) %>
    <% end %>
  </div>
  <h3 class="user-name"><%= @user_profile.full_name %> <small>(<%= @user_profile.role %>)</small></h3>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">Ciudad</div>
      <div class="panel-body"><%= @user_profile.city %></div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">Correo electrónico</div>
      <div class="panel-body"><%= mail_to @user_profile.email %></div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">Teléfono</div>
      <div class="panel-body"><%= number_to_phone @user_profile.phone %></div>
    </div>
  </div>

  <% if @user_profile.experience %>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">Años de experiencia en el sector</div>
        <div class="panel-body"><%= @user_profile.experience %></div>
      </div>
    </div>
  <% end %>
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">Propiedades publicadas</div>
      <div class="panel-body">
        <%= @user_profile.properties.count %>
        <%= link_to 'Ver propiedades', properties_user_profile_path(@user_profile) %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Acerca de mi</div>
      <div class="panel-body"><%= @user_profile.about %></div>
    </div>
  </div>
</div>

<p>
  <% if can? :edit, @user_profile %>
    <%= link_to 'Editar perfil', edit_user_profile_path(@user_profile), class: 'btn btn-primary' %>
  <% elsif user_signed_in? %>
    <%= link_to 'Agregar contacto', add_contact_user_profile_path(@user_profile), remote: true, id: 'add-contact-button',
      class: 'btn btn-success' unless current_user.is_contact?(@user_profile)
    %>
    <%= link_to 'Enviar mensaje', '#', class: 'btn btn-primary pull-right', data: { toggle: 'modal', target: '#new-message-modal' } %>
  <% else %>
    <%= link_to 'Contactar', '#', class: 'btn btn-success', data: { toggle: 'modal', target: '#contact-modal' } %>
  <% end %>
  <br>
  <br>
</p>

<% unless user_signed_in? %>
  <div id="contact-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Contactar Comisionista</h4>
        </div>
        <div class="modal-body">
          <p>Ingrese sus datos para contactar y contratar los servicios de este comisionista</p>
          <form>
            <div class="form-group">
              <%= text_field_tag :names, '', placeholder: 'Nombres', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= email_field_tag :email, '', placeholder: 'Correo electrónico', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= text_field_tag :subject, '', placeholder: 'Asunto', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= text_area_tag :content, '', placeholder: 'Mensaje', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= submit_tag 'Enviar', class: 'btn btn-primary' %>
              <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cancelar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div id="new-message-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Enviar mensaje a <%= @user_profile.first_name %></h4>
        </div>
        <div class="modal-body">
          <%= render 'messages/form', recipient: @user_profile.user %>
        </div>
      </div>
    </div>
  </div>
<% end %>